// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://frtkmwjterfzwmwxvjlq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZydGttd2p0ZXJmendtd3h2amxxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAxMzgyOTMsImV4cCI6MjA1NTcxNDI5M30.cytSYqM7k92SXv_IToAdobATpqdooR9kUuoHLECKtNE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);